site_name: Walltime Chronicles
site_url: https://zhipenghe.me/walltime-chronicles/
site_author: Zhipeng He
site_description: My personal survival log of mysterious errors, queueing oddities, and PBS quirks encountered on QUT Aqua

# repo_name: ZhipengHe/Walltime-Chronicles
repo_url: https://github.com/ZhipengHe/Walltime-Chronicles
edit_uri: edit/main/docs/

copyright: >
  Copyright &copy; 2025 Zhipeng He

theme:
  name: material
  language: en
  icon:
    logo: octicons/cpu-24
    # edit: material/pencil
    # view: material/eye
  features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - navigation.top
    - navigation.expand
    - content.action.view
    - content.action.edit
    - content.code.copy
    - content.code.select
    - content.code.annotate

plugins:
  - search
  - social
  - git-revision-date-localized:
      enabled: true
      enable_creation_date: true
      timezone: Australia/Brisbane
  - git-committers:
      repository: ZhipengHe/Walltime-Chronicles
      branch: main

extra:
  social:
    - icon: fontawesome/solid/house-chimney
      link: https://zhipenghe.me
    - icon: fontawesome/brands/github
      link: https://github.com/zhipenghe

markdown_extensions:
  - admonition
  - tables
  - attr_list
  - def_list
  - md_in_html
  - footnotes
  - pymdownx.details
  - pymdownx.betterem
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.blocks.caption
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css


nav:
  - "~/welcome": index.md
  - "Crash Course Café":
    - "Getting Started": tutorials/get-start.md
    - "Prerequisites Checklist": tutorials/prerequisites.md
    - "Lesson 0: HPC Fundamentals": tutorials/Lesson-0.md
    # - "Lesson 1: Environment Setup & First Interactive Session": tutorials/Lesson-1.md

  - "Cmd+Opt+Remote":
    - "Surviving without VS Code Remote SSH": remote-dev/Surviving-without-VS-Code-Remote-SSH.md
    - "The .DS_Store Strikes Back: Finder Edition": remote-dev/The-DS_Store-Strikes-Back.md
  - "The Scheduler's Gambit":
    - "Know Your Nodes": scheduler/Know-Your-Nodes.md
    - "Guess, Request, Regret: The Art of Walltime": scheduler/The-Art-of-Walltime.md
  - "PBS Cookbook":
    - "Batch-Cooking PBS Scripts with a Bash Pan": pbs-scripts/Batch-Cooking-PBS-Scripts-with-a-Bash-Pan.md
    - "PBS Brew Inspector: Tasting Notes from Your Job History": pbs-scripts/PBS-Brew-Inspector.md
  - License: LICENSE.md
